version: "3.8"

services:
  openai:
    container_name: openai
    restart: unless-stopped
    image: openai-production:1.0.0
    build:
      context: openai
      target: production
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - shared-network

  user:
    container_name: client-user
    restart: unless-stopped
    image: client-user-production:1.0.0
    build:
      context: ./clients/user
      target: production
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - shared-network
    depends_on:
      - openai

  dashboard:
    container_name: client-dashboard
    restart: unless-stopped
    image: client-dashboard-production:1.0.0
    build:
      context: ./clients/dashboard
      target: production
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - shared-network
    depends_on:
      - openai
    volumes:
      - ./clients/dashboard:/app/
      - /app/node_modules
      - /app/.next

  redis:
    container_name: redis
    hostname: redis
    image: redis
    command: >
      --include /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    networks:
      - shared-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - shared-network
networks:
  shared-network:
