import "./globals.css";
import { Poppins } from "next/font/google";
import AppProvider from "../Redux/AppProvider";
import { Toaster } from "react-hot-toast";

const popins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
      <link rel="shortcut icon" href="/favicon.png" />
      </head>
      <body className={popins.className}>
        <AppProvider>{children}</AppProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
